print('Oi delicia')
print('2*2')
print(2*2)
print(12, 34)
print(56,78)
print('Matheus Henrique dos Santos Silva','Eduarda',sep='')
dia=int(input('Digite o dia do seu aniversario: '))
mes=int(input('Digite o mês do seu aniversario: '))
ano=int(input('Digite o ano do seu aniversario: '))
print('{}/{}/{}'.format(dia,mes,ano))